### ISSUE TITLE
dhcp server appears to not be listening on opa0.8022 subnet

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_setup#46]
@JSpewock 

Attempts to get a dhcp address on the opa0 fabric work, but attempts to get a dhcp address on opa0.8022 do not.  Using manual IP assignment works fine.  It sounds like the base dhcp configuration file is missing a stanza for the opa0.8022 subnet, which should be the 172.31.22 subnet.  That or builder-00 does not actively have the opa0.8022 interface up and running.

**Comment by lylavoie** [comment]
This is fixed by Issues #63 builder setup was aligned to figure, which wasn't 100% accurate.
